//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Gen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP_Gen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- Dropping stored procedure {0:G} : 
        ///--
        ///
        ///IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[{0:G}]&apos;) AND OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///  DROP PROCEDURE [dbo].[{0:G}]
        ///  
        ///GO.
        /// </summary>
        internal static string DropProcedure {
            get {
                return ResourceManager.GetString("DropProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6:G}public {0:G}DataSet {1:G}({2:G})
        ///        {{
        ///            DbObject dbo = new DbObject();
        ///            SqlParameter[] parameters = new SqlParameter[]
        ///                {{
        ///{3:G} 
        ///                }};
        ///            return dbo.RunProcedure(&quot;{4:G}&quot;, parameters, &quot;{5:G}&quot;);
        ///        }}.
        /// </summary>
        internal static string ReturnDatasetMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnDatasetMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5:G}public {0:G}int {1:G}({2:G})
        ///		{{
        ///			int RowsAffected = 0;
        ///			int Result = 0;
        ///			DbObject dbo = new DbObject();
        ///			SqlParameter[] parameters = new SqlParameter[]
        ///				{{
        ///{3:G} 
        ///				}};
        ///			Result = dbo.RunProcedure(&quot;{4:G}&quot;, parameters, out RowsAffected);
        ///			return RowsAffected;
        ///        }}.
        /// </summary>
        internal static string ReturnRowsAffectedMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnRowsAffectedMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5:G}public {0:G}int {1:G}({2:G})
        ///		{{
        ///			int RowsAffected = 0;
        ///			int Result = 0;
        ///			DbObject dbo = new DbObject();
        ///			SqlParameter[] parameters = new SqlParameter[]
        ///				{{
        ///{3:G} 
        ///				}};
        ///			Result = dbo.RunProcedure(&quot;{4:G}&quot;, parameters, out RowsAffected);
        ///			return Result;
        ///        }}.
        /// </summary>
        internal static string ReturnScalarMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnScalarMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SqlParameter(&quot;{0:G}&quot;,{1:G}).
        /// </summary>
        internal static string SqlParameterTemplate {
            get {
                return ResourceManager.GetString("SqlParameterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbid AS ID, NULL AS ParentID, name AS Text FROM [master].[dbo].[sysdatabases] ORDER BY [name].
        /// </summary>
        internal static string strDatabasesList2000 {
            get {
                return ResourceManager.GetString("strDatabasesList2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT database_id AS ID, NULL AS ParentID, name AS Text FROM sys.databases ORDER BY [name].
        /// </summary>
        internal static string strDatabasesList2005 {
            get {
                return ResourceManager.GetString("strDatabasesList2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE {0:G};
        ///
        ///SELECT  Cols.TABLE_NAME,
        ///        Cols.COLUMN_NAME,
        ///        Cols.ORDINAL_POSITION,
        ///        Cols.DATA_TYPE,
        ///		Cols.NUMERIC_PRECISION,
        ///		Cols.NUMERIC_SCALE,		
        ///        Cols.IS_NULLABLE,
        ///        Cols.CHARACTER_MAXIMUM_LENGTH,       
        ///        COLUMNPROPERTY(object_id(Cols.TABLE_NAME), Cols.COLUMN_NAME, &apos;IsIdentity&apos;) AS IsIdentity,
        ///        ( SELECT    COUNT(KCU.COLUMN_NAME)
        ///          FROM      INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
        ///                    INNER JOIN INFORMATION_SCHEMA.TABLE_CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strTablesAndColumns {
            get {
                return ResourceManager.GetString("strTablesAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM [{0:G}].INFORMATION_SCHEMA.TABLES
        ///WHERE TABLE_TYPE = &apos;BASE TABLE&apos;  
        ///AND TABLE_NAME &lt;&gt; &apos;dtproperties&apos;  
        ///ORDER BY TABLE_NAME.
        /// </summary>
        internal static string strTablesList {
            get {
                return ResourceManager.GetString("strTablesList", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon table_sql_create {
            get {
                object obj = ResourceManager.GetObject("table_sql_create", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.ComponentModel;
        ///using NovinMedia.Data;
        ///
        ///namespace {0:G}
        ///{{
        ///    [DataObject(true)]
        ///    public class {1:G}
        ///    {{
        ///{2:G}
        ///    }}
        ///}}.
        /// </summary>
        internal static string WrapperClass_CSharp_Template {
            get {
                return ResourceManager.GetString("WrapperClass_CSharp_Template", resourceCulture);
            }
        }
    }
}
